#####################################################################################################################################################
#                                                        Assignment CMPT 120                                                                        #
#                                                        Authors- Murtaza Mushtaq and Wael Yacoub Agha                                              #
#####################################################################################################################################################
import turtle as t
import time
import random
t.speed(1000)
colors = ["red","black","orange","pink","purple","yellow"]
def fish(n):
    for i in range(3):
        t.pencolor("black")
        t.fd(12)
        t.right(120)
    t.penup
    t.right(60)
    t.forward(10)
    t.right(120)
    t.pendown
    t.begin_fill()
    t.fillcolor(n)
    t.circle(10)
    t.end_fill()
def location(s):
    t.write(s, move=False, align="left", font=("Arial", 30, "normal"))
def human():
    for i in range(6):
        t.pencolor("black")
        t.circle(8)
        t.right(90)
        t.forward(8)
        t.right(30)
        t.forward(15)
        t.penup()
        t.backward(15)
        t.pendown()
        t.left(60)
        t.forward(15)
        t.penup()
        t.backward(15)
        t.pendown()
        t.right(30)
        t.forward(15)
        t.right(30)
        t.forward(15)
        t.penup()
        t.backward(15)
        t.pendown()
        t.left(60)
        t.forward(15)
        t.penup()
        t.backward(15)
        t.right(30)
        t.penup()
        t.left(90)
        t.fd(80)
        t.left(90)
        t.fd(20)
        t.right(90)
        t.pendown()
    return
t.begin_fill()
t.fillcolor("green")
t.penup()
t.backward(150)
t.right(90)
t.fd(100)
t.left(90)
t.pendown()
for i in range(2):
    t.fd(600)
    t.left(90)
    t.fd(300)
    t.left(90)
t.end_fill()
t.penup()
t.home()
t.pendown()
t.begin_fill()
for i in range(2):
    t.fd(400)
    t.left(90)
    t.fd(150)
    t.left(90)
t.fillcolor("blue")
t.end_fill()
t.penup()
t.fd(100)
t.left(90)
t.pendown()
t.right(90)
for i in range(3):
    for i in range(3):
        for i in range(2):
            t.begin_fill()
            t.fd(150)
            t.left(90)
            t.fd(10)
            t.left(90)
            t.fillcolor("grey")
            t.end_fill()
        t.penup()
        t.fd(10)
        t.left(90)
        t.fd(10)
        t.right(90)
        t.pendown()
    t.penup()
    t.backward(20)
    t.pendown()
t.penup()
t.fd(160)
t.left(180)
t.pendown()
for i in range(2):
    for i in range(3):
        for i in range(2):
            t.begin_fill()
            t.fd(150)
            t.right(90)
            t.fd(10)
            t.right(90)
            t.fillcolor("grey")
            t.end_fill()
        t.penup()
        t.fd(10)
        t.right(90)
        t.fd(10)
        t.left(90)
        t.pendown()
    t.penup()
    t.backward(20)
    t.pendown()
t.end_fill()
t.penup()
t.fd(80)
t.pendown()
time.sleep(0.5)
location("SFU AQ Pond")
t.penup()
t.left(35)
t.fd(325)
t.right(215)
t.pendown()
human()
t.penup()
t.backward(40)
t.left(90)
t.fd(90)
t.pendown()
fish(random.choice(colors))
t.penup()
t.right(90)
t.fd(350)
t.pendown()
fish(random.choice(colors))
t.ht()


    
    
